export const QUESTION_LABELS: Record<string, string> = {
  residence_state: "Which U.S. state or territory do you live in?",
  residence_california_region: "Which California jurisdiction area do you live in?",
  age: "What is the applicant's age?",
  minor_15_17_validity: "Which passport validity is being requested?",
  has_existing_or_previous_passport: "Has the applicant ever held an Indian passport?",
  passport_validity: "What is the current passport status?",
  pages_exhausted: "Are the passport pages exhausted?",
  passport_lost_or_stolen: "Is the passport lost or stolen?",
  passport_damaged: "Is the passport damaged?",
  damaged_beyond_recognition: "Is it damaged beyond recognition?",
  change_existing_particulars: "Which passport particulars are changing?",
  requested_processing: "Which processing route do you want?",
  booklet: "Which booklet do you want?",
  one_parent_consent_missing: "Is consent from one parent unavailable?",
  government_form_already_submitted: "Have you already submitted the Government passport form?",
  government_selected_service: "Which service did you select on the Government form?",
  government_selected_mission: "Which Indian Mission did you select?",
  government_reason_matches: "Does the selected Re-issue reason match your situation?",
  government_arn: "Enter the Government application ARN",
  vfs_registration_complete: "Have you completed VFS registration?",
  vfs_reference_matches_government_arn: "Does the VFS reference match the Government ARN?",
  online_photo_uploaded: "Did you upload the photo online?",
  online_signature_uploaded: "Did you upload the signature online?"
};

export const OPTION_LABELS: Record<string, string> = {
  CA: "California",
  CO: "Colorado",
  HI: "Hawaii",
  UT: "Utah",
  WY: "Wyoming",
  GU: "Guam",
  AZ: "Arizona",
  NV: "Nevada",
  NM: "New Mexico",
  AS: "American Samoa",
  OTHER: "Another state / territory",
  northern_or_central: "Northern or Central California",
  southern_10_counties: "Southern California — Los Angeles jurisdiction",
  not_sure: "Not sure",
  until_age_18: "Valid until age 18",
  ten_year: "10-year validity",
  valid_not_due: "Valid and not close to expiry",
  due_to_expire: "Due to expire",
  expired_within_3_years: "Expired within the last 3 years",
  expired_more_than_3_years: "Expired more than 3 years ago",
  none: "No changes",
  name: "Name",
  spouse_name: "Spouse name",
  indian_address: "Indian address",
  usa_address: "U.S. address",
  appearance: "Appearance",
  signature: "Signature",
  date_of_birth: "Date of birth",
  place_of_birth: "Place of birth",
  father_name: "Father's name",
  mother_name: "Mother's name",
  sex: "Sex",
  regular: "Regular",
  tatkaal: "Tatkaal",
  ordinary_36_pages: "36-page booklet",
  jumbo_60_pages: "60-page jumbo booklet",
  fresh: "Fresh Passport",
  reissue: "Passport Re-issue",
  yes: "Yes",
  no: "No",
  san_francisco_direct: "San Francisco jurisdiction",
  los_angeles_transition_serviced_by_san_francisco: "Los Angeles jurisdiction — currently serviced through San Francisco",
  needs_jurisdiction_confirmation: "Jurisdiction needs confirmation"
};

export function labelOption(value: string): string {
  return OPTION_LABELS[value] ?? value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}
